[[colors.indexed_colors]]
color = "0xde935f"
index = 16

[[colors.indexed_colors]]
color = "0xa3685a"
index = 17

[[colors.indexed_colors]]
color = "0x282a2e"
index = 18

[[colors.indexed_colors]]
color = "0x373b41"
index = 19

[[colors.indexed_colors]]
color = "0xb4b7b4"
index = 20

[[colors.indexed_colors]]
color = "0xe0e0e0"
index = 21

[colors.bright]
black = "0x969896"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xffffff"
yellow = "0xf0c674"

[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[font]
size = 14.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "SemiBold"

[font.italic]
family = "Fira Code"
style = "SemiBold"

[font.normal]
family = "Fira Code"
style = "Regular"

[terminal.shell]
args = ["--login", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 0
y = 0

[terminal]
